// Code generated by ping-terraform-plugin-framework-generator

package customdomains

import (
	"context"
	"net/http"
	"time"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/setdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	client "github.com/pingidentity/identitycloud-go-client/identitycloud"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/auth"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/providererror"
	internaltypes "github.com/pingidentity/terraform-provider-identitycloud/internal/types"
	"github.com/sethvargo/go-retry"
)

var (
	_ resource.Resource                = &customDomainsResource{}
	_ resource.ResourceWithConfigure   = &customDomainsResource{}
	_ resource.ResourceWithImportState = &customDomainsResource{}
)

func CustomDomainsResource() resource.Resource {
	return &customDomainsResource{}
}

type customDomainsResource struct {
	apiClient   *client.APIClient
	accessToken string
}

func (r *customDomainsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_domains"
}

func (r *customDomainsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	resourceConfig, ok := req.ProviderData.(internaltypes.ResourceConfiguration)
	if !ok {
		resp.Diagnostics.AddError(providererror.InternalProviderError, "Invalid ProviderData when configuring resource. Please report this error in the provider's issue tracker.")
		return
	}
	r.apiClient = resourceConfig.ApiClient
	r.accessToken = resourceConfig.AccessToken
}

type customDomainsResourceModel struct {
	Domains  types.Set      `tfsdk:"domains"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
	Realm    types.String   `tfsdk:"realm"`
}

func (r *customDomainsResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	// domains default
	domainsDefault, diags := types.SetValue(types.StringType, nil)
	resp.Diagnostics.Append(diags...)

	resp.Schema = schema.Schema{
		Description: "Resource to create and manage the custom domains.",
		Attributes: map[string]schema.Attribute{
			"domains": schema.SetAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
				Description: "The custom domains. Defaults to an empty set.",
				Default:     setdefault.StaticValue(domainsDefault),
			},
			"realm": schema.StringAttribute{
				Optional:    true,
				Description: "Realm for the domain. Supported values are `alpha`, `bravo`.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf(
						"alpha",
						"bravo",
					),
				},
			},
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create:            true,
				CreateDescription: "A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as \"30s\" or \"2h45m\", as a time to wait for DNS record changes to propagate for verification on initial create of the resource. Valid time units are \"s\" (seconds), \"m\" (minutes), \"h\" (hours). The default is 1 minute.",
				Update:            true,
				UpdateDescription: "A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as \"30s\" or \"2h45m\", as a time to wait for DNS record changes to propagate for verification on update of the resource. Valid time units are \"s\" (seconds), \"m\" (minutes), \"h\" (hours). The default is 1 minute.",
			}),
		},
	}
}

func (model *customDomainsResourceModel) buildClientStruct() (*client.CustomDomains, diag.Diagnostics) {
	result := &client.CustomDomains{}
	// domains
	if !model.Domains.IsNull() {
		result.Domains = []string{}
		for _, domainsElement := range model.Domains.Elements() {
			result.Domains = append(result.Domains, domainsElement.(types.String).ValueString())
		}
	}

	return result, nil
}

// Build a default client struct to reset the resource to its default state
// If necessary, update this function to set any other values that should be present in the default state of the resource
func (model *customDomainsResource) buildDefaultClientStruct() *client.CustomDomains {
	result := &client.CustomDomains{}
	return result
}

func (state *customDomainsResourceModel) readClientResponseShouldRetry(ctx context.Context, response *client.CustomDomains, httpResp *http.Response, err error, diags *diag.Diagnostics) bool {
	var respDiags diag.Diagnostics
	// domains
	state.Domains, respDiags = types.SetValueFrom(context.Background(), types.StringType, response.Domains)
	diags.Append(respDiags...)

	if err == nil {
		return false
	}

	aicError, respBody := providererror.ReadErrorResponse(ctx, httpResp)
	if isFailedCnameValidation(aicError) {
		return true
	} else if !diags.HasError() {
		providererror.ReportHttpErrorBody(ctx, diags, "An error occurred while verifying the custom domain", err, respBody)
	}
	return false
}

func (r *customDomainsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data customDomainsResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	// Retry up to the time limit on create
	createTimeout, diags := data.Timeouts.Create(ctx, 1*time.Minute)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Update API call logic, since this is a singleton resource
	clientData, diags := data.buildClientStruct()
	resp.Diagnostics.Append(diags...)
	apiUpdateRequest := r.apiClient.CustomDomainsAPI.SetCustomDomains(auth.AuthContext(ctx, r.accessToken), data.Realm.ValueString())
	apiUpdateRequest = apiUpdateRequest.Body(*clientData)

	retries := retry.NewFibonacci(1 * time.Second)
	retries = retry.WithMaxDuration(createTimeout, retries)
	var responseData *client.CustomDomains
	var httpResp *http.Response
	var err error
	retry.Do(ctx, retries, func(ctx context.Context) error {
		responseData, httpResp, err = r.apiClient.CustomDomainsAPI.SetCustomDomainsExecute(apiUpdateRequest)
		if data.readClientResponseShouldRetry(ctx, responseData, httpResp, err, &resp.Diagnostics) {
			return retry.RetryableError(err)
		}
		return err
	})

	if err != nil {
		providererror.ReportHttpError(ctx, &resp.Diagnostics, "An error occurred while creating the customDomains", err, httpResp)
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *customDomainsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data customDomainsResourceModel

	// Read Terraform prior state data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Read API call logic
	responseData, httpResp, err := r.apiClient.CustomDomainsAPI.GetCustomDomains(auth.AuthContext(ctx, r.accessToken), data.Realm.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			providererror.AddResourceNotFoundWarning(ctx, &resp.Diagnostics, "customDomains", httpResp)
			resp.State.RemoveResource(ctx)
		} else {
			providererror.ReportHttpError(ctx, &resp.Diagnostics, "An error occurred while reading the customDomains", err, httpResp)
		}
		return
	}

	// Read response into the model
	data.readClientResponseShouldRetry(ctx, responseData, httpResp, err, &resp.Diagnostics)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *customDomainsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data customDomainsResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	// Retry up to the time limit on update
	updateTimeout, diags := data.Timeouts.Update(ctx, 1*time.Minute)
	resp.Diagnostics.Append(diags...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Update API call logic
	clientData, diags := data.buildClientStruct()
	resp.Diagnostics.Append(diags...)
	apiUpdateRequest := r.apiClient.CustomDomainsAPI.SetCustomDomains(auth.AuthContext(ctx, r.accessToken), data.Realm.ValueString())
	apiUpdateRequest = apiUpdateRequest.Body(*clientData)

	retries := retry.NewFibonacci(1 * time.Second)
	retries = retry.WithMaxDuration(updateTimeout, retries)
	var responseData *client.CustomDomains
	var httpResp *http.Response
	var err error
	retry.Do(ctx, retries, func(ctx context.Context) error {
		responseData, httpResp, err = r.apiClient.CustomDomainsAPI.SetCustomDomainsExecute(apiUpdateRequest)
		if data.readClientResponseShouldRetry(ctx, responseData, httpResp, err, &resp.Diagnostics) {
			return retry.RetryableError(err)
		}
		return err
	})

	if err != nil {
		providererror.ReportHttpError(ctx, &resp.Diagnostics, "An error occurred while updating the customDomains", err, httpResp)
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *customDomainsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// This resource is singleton, so it can't be deleted from the service.
	// Instead this delete method will attempt to set the resource to its default state on the service. If this isn't possible,
	// this method can be replaced with a no-op with a diagnostic warning message about being unable to set to the default state.
	var data customDomainsResourceModel

	// Read Terraform plan data into the model
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Update API call logic to reset to default
	defaultClientData := r.buildDefaultClientStruct()
	apiUpdateRequest := r.apiClient.CustomDomainsAPI.SetCustomDomains(auth.AuthContext(ctx, r.accessToken), data.Realm.ValueString())
	apiUpdateRequest = apiUpdateRequest.Body(*defaultClientData)
	_, httpResp, err := r.apiClient.CustomDomainsAPI.SetCustomDomainsExecute(apiUpdateRequest)
	if err != nil {
		providererror.ReportHttpError(ctx, &resp.Diagnostics, "An error occurred while resetting the customDomains", err, httpResp)
	}
}

func (r *customDomainsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Retrieve import ID and save to realm attribute
	resource.ImportStatePassthroughID(ctx, path.Root("realm"), req, resp)
}
