// Code generated by ping-terraform-plugin-framework-generator

package customdomains_test

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/acctest"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/provider"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/utils"
)

const customDomainsRealm = "alpha"

var customDomainsTestServerUrl *string

func TestAccCustomDomains_MinimalMaximal(t *testing.T) {
	if strings.ToLower(os.Getenv("PINGAIC_TF_TEST_MOCK_SERVICE")) == "true" {
		testServer := customDomains_MockHttpServer()
		customDomainsTestServerUrl = utils.Pointer(testServer.URL)
		os.Setenv("PINGAIC_TF_TEST_OVERRIDE_URL", testServer.URL)
		defer testServer.Close()
	}
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"identitycloud": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: customDomains_MinimalHCL(),
				Check:  customDomains_CheckComputedValuesMinimal(),
			},
			{
				// Update to a complete model. No computed values to check.
				Config: customDomains_CompleteHCL(),
			},
			{
				// Test importing the resource
				Config:                               customDomains_CompleteHCL(),
				ResourceName:                         "identitycloud_custom_domains.example",
				ImportStateId:                        customDomainsRealm,
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "realm",
			},
			{
				// Back to minimal model
				Config: customDomains_MinimalHCL(),
				Check:  customDomains_CheckComputedValuesMinimal(),
			},
		},
	})
}

// Minimal HCL with only required values set
func customDomains_MinimalHCL() string {
	return fmt.Sprintf(`
resource "identitycloud_custom_domains" "example" {
  realm = "%s"
}
`, customDomainsRealm)
}

// Maximal HCL with all values set where possible
func customDomains_CompleteHCL() string {
	return fmt.Sprintf(`
resource "identitycloud_custom_domains" "example" {
  realm = "%s"
  domains = ["%s"]
  timeouts = {
    create = "5s"
	update = "10s"
  }
}
`, customDomainsRealm, os.Getenv("PINGAIC_TF_TENANT_ENV_FQDN"))
}

// Validate any computed values when applying minimal HCL
func customDomains_CheckComputedValuesMinimal() resource.TestCheckFunc {
	return resource.TestCheckResourceAttr("identitycloud_custom_domains.example", "domains.#", "0")
}

// Mocking the AIC service for testing
type domains struct {
	Domains []string `json:"domains"`
}

var testDomains = domains{
	Domains: []string{},
}

func customDomains_MockHttpServer() *httptest.Server {
	return httptest.NewTLSServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var out []byte
		switch r.Method {
		case http.MethodGet:
			out, _ = json.Marshal(testDomains)
		case http.MethodPut:
			var inputDomains domains
			err := json.NewDecoder(r.Body).Decode(&inputDomains)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			testDomains.Domains = inputDomains.Domains
			out, _ = json.Marshal(testDomains)
		}
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Content-API-Version", "1.0")
		w.WriteHeader(http.StatusOK)
		w.Write(out)
	}))
}
