// Code generated by ping-terraform-plugin-framework-generator

package customdomains_test

import (
	"fmt"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/acctest"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/provider"
)

const customDomainsRealm = "alpha"

func TestAccCustomDomains_MinimalMaximal(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"identitycloud": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: customDomains_MinimalHCL(),
				Check:  customDomains_CheckComputedValuesMinimal(),
			},
			{
				// Update to a complete model. No computed values to check.
				Config: customDomains_CompleteHCL(),
			},
			{
				// Test importing the resource
				Config:                               customDomains_CompleteHCL(),
				ResourceName:                         "identitycloud_custom_domains.example",
				ImportStateId:                        customDomainsRealm,
				ImportState:                          true,
				ImportStateVerify:                    true,
				ImportStateVerifyIdentifierAttribute: "realm",
			},
			{
				// Back to minimal model
				Config: customDomains_MinimalHCL(),
				Check:  customDomains_CheckComputedValuesMinimal(),
			},
		},
	})
}

// Minimal HCL with only required values set
func customDomains_MinimalHCL() string {
	return fmt.Sprintf(`
resource "identitycloud_custom_domains" "example" {
  realm = "%s"
}
`, customDomainsRealm)
}

// Maximal HCL with all values set where possible
func customDomains_CompleteHCL() string {
	return fmt.Sprintf(`
resource "identitycloud_custom_domains" "example" {
  realm = "%s"
  domains = ["%s"]
  timeouts = {
    create = "5s"
	update = "10s"
  }
}
`, customDomainsRealm, os.Getenv("PINGAIC_TF_TENANT_ENV_FQDN"))
}

// Validate any computed values when applying minimal HCL
func customDomains_CheckComputedValuesMinimal() resource.TestCheckFunc {
	return resource.TestCheckResourceAttr("identitycloud_custom_domains.example", "domains.#", "0")
}
