// Code generated by ping-terraform-plugin-framework-generator

package contentsecuritypolicy_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/acctest"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/provider"
)

func TestAccContentSecurityPolicyReportOnly_MinimalMaximal(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"identitycloud": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: contentSecurityPolicyReportOnly_MinimalHCL(),
				Check:  contentSecurityPolicyReportOnly_CheckComputedValuesMinimal(),
			},
			{
				// Update to a complete model
				Config: contentSecurityPolicyReportOnly_CompleteHCL(),
			},
			{
				// Test importing the resource
				Config:                               contentSecurityPolicyReportOnly_CompleteHCL(),
				ResourceName:                         "identitycloud_content_security_policy_report_only.example",
				ImportStateVerifyIdentifierAttribute: "active",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
			{
				// Back to minimal model
				Config: contentSecurityPolicyReportOnly_MinimalHCL(),
				Check:  contentSecurityPolicyReportOnly_CheckComputedValuesMinimal(),
			},
		},
	})
}

// Minimal HCL with only required values set
func contentSecurityPolicyReportOnly_MinimalHCL() string {
	return `
resource "identitycloud_content_security_policy_report_only" "example" {
}
`
}

// Maximal HCL with all values set where possible
func contentSecurityPolicyReportOnly_CompleteHCL() string {
	return `
resource "identitycloud_content_security_policy_report_only" "example" {
  active = true
  directives = {
    "key" = ["value1", "value2"] 
  }
}
`
}

// Validate any computed values when applying minimal HCL
func contentSecurityPolicyReportOnly_CheckComputedValuesMinimal() resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr("identitycloud_content_security_policy_report_only.example", "active", "false"),
		resource.TestCheckResourceAttr("identitycloud_content_security_policy_report_only.example", "directives.#", "0"),
	)
}
