// Code generated by ping-terraform-plugin-framework-generator

package ssocookie_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/acctest"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/provider"
)

func TestAccSsoCookie_MinimalMaximal(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"identitycloud": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: ssoCookie_MinimalHCL(),
			},
			{
				// Update to a complete model
				Config: ssoCookie_UpdatedHCL(),
			},
			{
				// Test importing the resource
				Config:                               ssoCookie_UpdatedHCL(),
				ResourceName:                         "identitycloud_sso_cookie.example",
				ImportStateVerifyIdentifierAttribute: "name",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
			{
				// Back to minimal model
				Config: ssoCookie_MinimalHCL(),
			},
		},
	})
}

// Minimal HCL with only required values set
func ssoCookie_MinimalHCL() string {
	return `
resource "identitycloud_sso_cookie" "example" {
  name = "initial"
}
`
}

// Maximal HCL with all values set where possible
func ssoCookie_UpdatedHCL() string {
	return `
resource "identitycloud_sso_cookie" "example" {
  name = "updated"
}
`
}
