// Code generated by ping-terraform-plugin-framework-generator

package secrets_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/acctest"
	"github.com/pingidentity/terraform-provider-identitycloud/internal/provider"
)

const secretVersionSecretId = "esv-secretversiontest"
const secretVersionVersionId = "3"

var secretVersionTestServerUrl *string

func TestAccSecretVersion_RemovalDrift(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"identitycloud": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		CheckDestroy: secretVersion_CheckDestroy,
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: secretVersion_MinimalHCL(),
			},
			{
				// Delete the resource on the service, outside of terraform, verify that a non-empty plan is generated
				PreConfig: func() {
					secretVersion_Delete(t)
				},
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
			},
		},
	})
}

func TestAccSecretVersion_MinimalMaximal(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"identitycloud": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		CheckDestroy: secretVersion_CheckDestroy,
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: secretVersion_MinimalHCL(),
				Check:  secretVersion_CheckComputedValuesMinimal(),
			},
			{
				// Delete the minimal model
				Config:  secretVersion_MinimalHCL(),
				Destroy: true,
			},
			{
				// Re-create with a complete model
				Config: secretVersion_CompleteHCL(),
				Check:  secretVersion_CheckComputedValuesComplete(),
			},
			{
				// Back to minimal model
				Config: secretVersion_MinimalHCL(),
				Check:  secretVersion_CheckComputedValuesMinimal(),
			},
			{
				// Back to complete model
				Config: secretVersion_CompleteHCL(),
				Check:  secretVersion_CheckComputedValuesComplete(),
			},
			{
				// Test importing the resource
				Config:                               secretVersion_CompleteHCL(),
				ResourceName:                         "identitycloud_secret_version.example",
				ImportStateId:                        secretVersionSecretId + "/" + secretVersionVersionId,
				ImportStateVerifyIdentifierAttribute: "version_id",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
		},
	})
}

// Minimal HCL with only required values set
func secretVersion_MinimalHCL() string {
	return fmt.Sprintf(`
resource "identitycloud_secret" "example" {
  secret_id = "%s"
  encoding = "generic"
  use_in_placeholders = false
  value_base64 = base64encode("examplesecret")
}

resource "identitycloud_secret_version" "example" {
  secret_id = identitycloud_secret.example.secret_id
  value_base64 = base64encode("examplesecretnewversion")
}
`, secretVersionSecretId)
}

// Maximal HCL with all values set where possible
func secretVersion_CompleteHCL() string {
	return fmt.Sprintf(`
resource "identitycloud_secret" "example" {
	secret_id = "%s"
	encoding = "generic"
	use_in_placeholders = false
	value_base64 = base64encode("examplesecret")
  }
  
  resource "identitycloud_secret_version" "example" {
	secret_id = identitycloud_secret.example.secret_id
	value_base64 = base64encode("examplesecretanotherversion")
	status = "ENABLED"
  }
`, secretVersionSecretId)
}

// Validate any computed values when applying minimal HCL
func secretVersion_CheckComputedValuesMinimal() resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttrSet("identitycloud_secret_version.example", "create_date"),
		resource.TestCheckResourceAttr("identitycloud_secret_version.example", "loaded", "expected_value"),
		resource.TestCheckResourceAttr("identitycloud_secret_version.example", "status", "expected_value"),
		resource.TestCheckResourceAttr("identitycloud_secret_version.example", "version", "expected_value"),
	)
}

// Validate any computed values when applying complete HCL
func secretVersion_CheckComputedValuesComplete() resource.TestCheckFunc {
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttrSet("identitycloud_secret_version.example", "create_date"),
		resource.TestCheckResourceAttr("identitycloud_secret_version.example", "loaded", "expected_value"),
		resource.TestCheckResourceAttr("identitycloud_secret_version.example", "version", "expected_value"),
	)
}

// Delete the resource
func secretVersion_Delete(t *testing.T) {
	testClient := acctest.Client(secretVersionTestServerUrl)
	_, _, err := testClient.SecretsAPI.DeleteSecretVersion(acctest.AuthContext(), secretVersionSecretId, secretVersionVersionId).Execute()
	if err != nil {
		t.Fatalf("Failed to delete config: %v", err)
	}
}

// Test that any objects created by the test are destroyed
func secretVersion_CheckDestroy(s *terraform.State) error {
	testClient := acctest.Client(secretVersionTestServerUrl)
	_, _, err := testClient.SecretsAPI.DeleteSecretVersion(acctest.AuthContext(), secretVersionSecretId, secretVersionVersionId).Execute()
	if err == nil {
		return fmt.Errorf("secret_version still exists after tests. Expected it to be destroyed")
	}
	return nil
}
