name: Scheduled Acceptance Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  acceptance:
    name: Acceptance Tests
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.4.*"
          - "1.5.*"
          - "1.6.*"
      max-parallel: 1
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: make testacc
        env:
          TF_ACC: "1"
          PINGAIC_TF_SERVICE_ACCOUNT_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}
          PINGAIC_TF_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
          PINGAIC_TF_TENANT_ENV_FQDN: ${{ secrets.PINGAIC_TF_TENANT_ENV_FQDN }}
  promotionacceptance:
    # Note: if this fails, it may be necessary to manually unlock the environment with the API to allow other tests to succeed
    name: Promotion Lock Acceptance Tests
    needs: [acceptance]
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - "1.6.*"
      max-parallel: 1
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: make testaccpromotion
        env:
          TF_ACC: "1"
          PINGAIC_TF_SERVICE_ACCOUNT_ID: ${{ secrets.SERVICE_ACCOUNT_ID }}
          PINGAIC_TF_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
          PINGAIC_TF_TENANT_ENV_FQDN: ${{ secrets.PINGAIC_TF_TENANT_ENV_FQDN }}
